# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
# Attention: Secrets are required to be defined in GitHub for this script to work.

name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml
    
    - name: Build the Image and Push to Registry
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build --tag ${{ secrets.DOCKER_USERNAME }}/${{ secrets.GREET_DOCKER_REPO }}:${{github.sha}} .
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.GREET_DOCKER_REPO }}:${{github.sha}}
    
    - name: Login to OC Cluster
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: https://${{ secrets.OC_URL }}:6443
        openshift_token: ${{ secrets.OC_TOKEN }}
        insecure_skip_tls_verify: true
        namespace: ${{ secrets.OC_NAMESPACE }}
        
    - name: Deploy the App in OC Cluster                
      run: |
        sed -i'' -e 's/DOCKER_USERNAME/${{ secrets.DOCKER_USERNAME }}/g' -e 's/NAME_SPACE/${{ secrets.OC_NAMESPACE }}/g' -e 's/OC_RT_URL/${{ secrets.OC_RT_URL }}/g' -e 's/IMAGE_LABEL/${{ github.sha }}/g' k8s.yaml
        oc apply -f k8s.yaml            
